### ISSUE TITLE
Device Config - Production server - Styling change

### ISSUE THREAD

**Issue by Kyle-Swanepoel** [solarmd-pty-ltd/myPower24-WEB#180]
Hi Team,

Can we please change the element.style for the "Modbus Settings" accordion to "display: contents;

It will just make it easier when working with the drop downs. 

Thanks

![image](https://user-images.githubusercontent.com/72873730/226869365-1a7a83f8-a941-4742-8e42-0b201c52d835.png)

**Comment by henry-thomas** [comment]
The reason for this behavior is the overflow within the accordion panel's content div. Setting the display to 'content' essentially removes the wrapper div, which will remove the overflow, and users will be forced to scroll the entire page in some cases. 

Won't fix because it's hard to choose which is the lesser evil.
